- entries:
  - jsonPayload:
      message: |-
        Jul 09, 2015 3:23:29 PM com.google.devtools.search.cloud.feeder.MakeLog: RuntimeException: Run from this message!
          at com.my.app.Object.do$a1(MakeLog.java:50)
          at java.lang.Thing.call(Thing.java:10)
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        Traceback (most recent call last):
          File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
            rv = self.handle_exception(request, response, e)
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 17, in start
            return get()
          File "/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py", line 5, in get
            raise Exception('spam', 'eggs')
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: "Exception: ('spam', 'eggs')"
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        javax.servlet.ServletException: Something bad happened
            at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
            at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
            at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
            at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
            at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
            at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
            at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
            at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
            at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
            at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
            at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
            at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
            at org.mortbay.jetty.Server.handle(Server.java:326)
            at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
            at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
            at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
            at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
            at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
            at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
            at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
        Caused by: com.example.myproject.MyProjectServletException
            at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
            at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
            at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
            at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
            ... 27 common frames omitted
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        java.lang.RuntimeException: javax.mail.SendFailedException: Invalid Addresses;
          nested exception is:
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:236)
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:285)
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.lambda$sendSingleEmail$3(AutomaticEmailFacade.java:254)
        	at java.util.Optional.ifPresent(Optional.java:159)
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:253)
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendSingleEmail(AutomaticEmailFacade.java:249)
        	at com.nethunt.crm.api.email.EmailSender.lambda$notifyPerson$0(EmailSender.java:80)
        	at com.nethunt.crm.api.util.ManagedExecutor.lambda$execute$0(ManagedExecutor.java:36)
        	at com.nethunt.crm.api.util.RequestContextActivator.lambda$withRequestContext$0(RequestContextActivator.java:36)
        	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        	at java.base/java.lang.Thread.run(Thread.java:748)
        Caused by: javax.mail.SendFailedException: Invalid Addresses;
          nested exception is:
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
        	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
        	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
        	at com.nethunt.crm.api.server.adminsync.AutomaticEmailFacade.sendWithSmtp(AutomaticEmailFacade.java:229)
        	... 12 more
        Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 <[REDACTED_EMAIL_ADDRESS]>... Relaying denied
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        Traceback (most recent call last):
          File "/test/exception.py", line 21, in <module>
            conn.request("GET", "/")
          File "/usr/lib/python3.10/http/client.py", line 1282, in request
            self._send_request(method, url, body, headers, encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
            self.endheaders(body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
            self._send_output(message_body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
            self.send(msg)
          File "/usr/lib/python3.10/http/client.py", line 975, in send
            self.connect()
          File "/usr/lib/python3.10/http/client.py", line 941, in connect
            self.sock = self._create_connection(
          File "/usr/lib/python3.10/socket.py", line 824, in create_connection
            for res in getaddrinfo(host, port, 0, SOCK_STREAM):
          File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno -2] Name or service not known
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: |-
        Traceback (most recent call last):
          File "/usr/local/google/home/lujieduan/source/test/exception.py", line 11, in <module>
            '2' + 2
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  - jsonPayload:
      message: "TypeError: can only concatenate str (not \"int\") to str"
    labels:
      compute.googleapis.com/resource_name: hostname
    logName: projects/my-project/logs/my-log-name
    resource:
      labels:
        instance_id: test-instance-id
        zone: test-zone
      type: gce_instance
    timestamp: now
  partialSuccess: true
